CREATE TABLE IF NOT EXISTS cars.question(
    ID BIGINT NOT NULL PRIMARY KEY,
    QUESTION VARCHAR(255) NOT NULL,
    ANSWER DECIMAL(10, 2) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS cars.question_seq
INCREMENT 1
START 1;