spring:
  datasource:
    url: ${JAVA_COURSE_DB_URL}
    username: ${JAVA_COURSE_DB_USER}
    password: ${JAVA_COURSE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: cars
jwt:
  secret-key: ${JAVA_COURSE_JWT_KEY}
cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket-name: java-course-final-project
      folder-name: CarImagesForFinalProject
server:
  port: 8888